[package]
name = "tei-py"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
tei-core = { path = "../tei-core" }
tei-serde = { workspace = true }
tei-xml = { path = "../tei-xml", features = ["streaming"] }
pyo3 = { version = "0.24.2", features = ["auto-initialize"] }
pyo3-serde = { package = "serde-pyobject", version = "0.6.2" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
rstest-bdd = { workspace = true }
rstest-bdd-macros = { workspace = true }
anyhow = { workspace = true }
tei-test-helpers = { path = "../tei-test-helpers" }

[build-dependencies]
pyo3-build-config = { version = "0.28.3", features = ["resolve-config"] }
